config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'data_sets#index', as: 'authenticated_root'
  end

  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :data_sets, only: [ :index, :show, :create, :update, :destroy ] do
    post :build, on: :member
    post :retrieve_build, on: :member
    get :build_status, on: :member
    post :cancel_build, on: :member
  end

  resources :profiles, only: [ :show, :create, :update, :destroy ] do
    post :change_proportion, on: :member
    post :toggle_required, on: :member
  end

  resources :entities, only: [ :show, :create, :update, :destroy ] do
    post :change_parent, on: :member
    post :change_rec_count, on: :member
  end

  resources :attrs, only: [ :show, :create, :update, :destroy ] do
    post :toggle_transient, on: :member
    post :setup_profile, on: :member
  end

  resources :attr_vals, only: [ :create, :destroy ] do
    post :setup_conditions, on: :member
  end

  resources :conditions, only: [ :create, :destroy ]

end

app/models/data_set.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

class DataSet < ActiveRecord::Base
  belongs_to :user

  has_many  :entities,    dependent: :delete_all
  has_one   :build_data,  dependent: :delete

  validates :name, format: { with: /\A[a-zA-Z]\w*\z/ }  # keep in sync with validateDataSetName() in home.js

  def to_s
    name
  end

  def entities_sorted_hierarchically(parent_entity_id = nil)
    arr = []
    entities.where(parent_entity_id: parent_entity_id).order(:name).each do |entity|
      arr << entity
      arr << entities_sorted_hierarchically(entity.id)
    end
    arr.flatten
  end

  def create_database_stmt
    "drop database if exists #{name};\ncreate database #{name};\nuse #{name};\n"
  end
end

app/controllers/data_sets_controller.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

require 'fileutils'
require 'tmpdir'
require 'securerandom'
require 'zip_util'
require 'executor_pool'
require 'execution_plan'
require 'build_manager'
require 'logging'

class DataSetsController < ApplicationController
  include Logging

  before_action :authenticate_user!
  before_action :set_data_set, only: [:show, :update, :destroy, :build, :retrieve_build, :build_status, :cancel_build]

  respond_to :html

  def index
    @data_sets = DataSet.where(user: current_user)
    respond_with(@data_sets)
  end

  def show
    respond_with(@data_set)
  end

  # def new
  #   @data_set = DataSet.new
  #   respond_with(@data_set)
  # end

  # def edit
  # end

  def create
    begin
      data_set = DataSet.create(data_set_params.merge(user: current_user))
      @error = data_set.errors.values.join('; ') if data_set.errors.any?

    rescue Exception => e
      @error = e.class.to_s
      log_error e
    end

    do_ajax_response
  end

  def update
    @data_set.update(data_set_params)
    respond_with(@data_set)
  end

  def destroy
    @data_set.destroy
    do_ajax_response
  end

  def build
    if @data_set.build_data.nil? || @data_set.build_data.may_rebuild?
      do_build
    end

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def retrieve_build
    build_data = @data_set.build_data
    if build_data && build_data.status == BuildData::STATUS_COMPLETED
      zip_data = File.read build_export_path.join(build_data.file)
      send_data zip_data, type: 'application/zip', filename: zip_filename_for(@data_set)
      destroy_current_build

    else
      redirect_to @data_set, flash: { error: 'Build does not exist for the specified data set' }
    end
  end

  def build_status
    respond_to do |format|
      format.html { render layout: false }
    end
  end

  def cancel_build
    BuildManager.instance.cancel_build_for current_user, @data_set
    @data_set.build_data.update(status: BuildData::STATUS_CANCELING) if @data_set.build_data

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    def do_build
      destroy_current_build

      export_path = build_export_path
      Dir.mkdir(export_path) unless Dir.exists?(export_path)

      build_data = BuildData.create(
          user:       current_user,
          data_set:   @data_set,
          thread_id:  SecureRandom.hex(5),
          status:     BuildData::STATUS_PREPARING)

      ExecutorPool.instance.execute(thread_id: build_data.thread_id) do
        begin
          Dir.mktmpdir do |dir|
            plan = ExecutionPlan.new(current_user, @data_set)

            build_data.update(status: BuildData::STATUS_RUNNING)

            plan.execute(dir)

            zip_file = ZipUtil.create_zip(dir)
            target_filename = "#{SecureRandom.hex(10)}.zip"

            FileUtils.move zip_file, export_path.join(target_filename)

            build_data.update(status: BuildData::STATUS_COMPLETED, file: target_filename)
          end

        rescue CanceledException
          log.info "thread #{build_data.thread_id} has been canceled."
          build_data.update(status: BuildData::STATUS_CANCELED)

        rescue Exception => e
          log_error e, 'building data'
          build_data.update(status: BuildData::STATUS_ERROR, message: e.message)
        end
      end
    end

    def destroy_current_build
      if @data_set.build_data
        File.delete(build_export_path.join(@data_set.build_data.file)) if @data_set.build_data.file
        @data_set.build_data.destroy
      end
    end

    def build_export_path
      # todo : perhaps the builds path shouldn't be under Rails.root?
      Rails.root.join('builds')
    end

    def zip_filename_for(data_set)
      name = data_set.name.strip
                 .gsub(/[^a-zA-Z0-9_ -]/, '')
                 .gsub(/\s+/, '_')
      "#{name}_data.zip"
    end

    def set_data_set
      @data_set = DataSet.where(user: current_user).find(params[:id])
    end

    def do_ajax_response
      @data_sets = DataSet.where(user: current_user)
      respond_to do |format|
        format.js { render layout: false }
      end
    end

    def data_set_params
      params.require(:data_set).permit(:user_id, :name, :desc)
    end
end

app/helpers/data_sets_helper.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

module DataSetsHelper
end

app/views/data_sets/_build.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- if data_set.build_data
  - status_url = build_status_data_set_path(data_set)
  - bd = data_set.build_data
  - if bd.status == BuildData::STATUS_PREPARING
    #build_progress{ data: { url: status_url } }
      Preparing to build.  Please wait.
      = render partial: 'cancel_build_form', locals: { data_set: data_set }

  - elsif bd.status == BuildData::STATUS_RUNNING
    - build_info = bd.current_build_info
    - c = build_info[:current]
    - t = build_info[:total]
    #build_progress{ data: { url: status_url } }
      = "Build is running.  Generated #{c} of #{t} records (#{((c.to_f / t) * 100).to_i}%)"
      %br
      = render partial: 'cancel_build_form', locals: { data_set: data_set }

  - elsif bd.status == BuildData::STATUS_CANCELING
    #build_progress{ data: { url: status_url } } Canceling build...

  - elsif bd.status == BuildData::STATUS_COMPLETED
    #build_completed
      = "Build completed successfully.  Took #{(bd.updated_at - bd.created_at).to_i} seconds."
      = form_tag(retrieve_build_data_set_path(data_set), id: 'retrieveBuildForm') do
        = submit_tag 'Retrieve Generated Records'
    = render partial: 'generate_records_form', locals: { data_set: data_set }

  - elsif bd.status == BuildData::STATUS_CANCELED
    #build_canceled Build has been successfully canceled.
    = render partial: 'generate_records_form', locals: { data_set: data_set }

  - elsif bd.status == BuildData::STATUS_ERROR
    #build_error
      = "Build failed with error: #{data_set.build_data.message}"
      %br
      If this error persists, please contact the system administrator.
    = render partial: 'generate_records_form', locals: { data_set: data_set }

  - else
    #build_error= "unhandled build status: #{bd.status}"
    = render partial: 'generate_records_form', locals: { data_set: data_set }

- else
  = render partial: 'generate_records_form', locals: { data_set: data_set }

app/views/data_sets/_cancel_build_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= form_tag(cancel_build_data_set_path(data_set), id: 'cancelBuildForm', remote: true) do
  = submit_tag 'Cancel'

app/views/data_sets/_generate_records_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= form_tag(build_data_set_path(data_set), id: 'buildDataSetForm', remote: true) do
  = submit_tag 'Generate Records'

app/views/data_sets/_list.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- if data_sets.any?
  %table.index
    %tr
      %th Name
      %th

    - data_sets.each do |data_set|
      %tr
        %td= link_to data_set.name, data_set
        %td= link_to 'Destroy', data_set, :method => :delete, :remote => true, :data => { :confirm => 'Are you sure?' }

app/views/data_sets/build.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#build_container').html("<%= j render(partial: 'data_sets/build', locals: { data_set: @data_set }) %>");
buildProgressPoll();

app/views/data_sets/build_status.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= render partial: 'data_sets/build', locals: { data_set: @data_set }

app/views/data_sets/cancel_build.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#build_container').html("<%= j render(partial: 'data_sets/build', locals: { data_set: @data_set }) %>");

app/views/data_sets/create.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

var error = "<%= @error %>";
if (error != '') {
    $('#new_data_set_form').find('span.error').html(error);

} else {
    $('#new_data_set_form').find('span.error').html('');
    $('#data_set_name').val('');
    $('#data_sets').html("<%= j render(partial: 'list', locals: { data_sets: @data_sets }) %>");
}

app/views/data_sets/destroy.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#data_sets').html("<%= j render(partial: 'list', locals: { data_sets: @data_sets }) %>");

app/views/data_sets/index.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

%h2 My Data Sets

#new_data_set_form
  = form_tag(data_sets_path, remote: true) do
    = label_tag 'data_set[name]', 'New data set:'
    = text_field_tag 'data_set[name]'
    = submit_tag 'Save'
    %span.error

#data_sets= render partial: 'list', locals: { data_sets: @data_sets }

app/views/data_sets/show.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

%h2 '#{@data_set.name}' data set

- content_for :path do
  %ul
    %li= link_to @data_set.name, @data_set

#build_container{ data: { id: @data_set.id } }= render partial: 'build', locals: { data_set: @data_set }

= form_for @data_set do |f|
  = f.label :name, 'Rename Data Set to:'
  = f.text_field :name
  = f.submit 'Rename'

%br

= form_tag(entities_path, remote: true, id: 'new_entity_form') do
  = hidden_field_tag 'entity[data_set_id]', @data_set.id
  = label_tag 'entity[name]', 'New entity:'
  = text_field_tag 'entity[name]'
  = submit_tag 'Save'
  %span.error

#entities= render partial: 'entities/list', locals: { entities: @data_set.entities_sorted_hierarchically }