config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'data_sets#index', as: 'authenticated_root'
  end

  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :data_sets, only: [ :index, :show, :create, :update, :destroy ] do
    post :build, on: :member
    post :retrieve_build, on: :member
    get :build_status, on: :member
    post :cancel_build, on: :member
  end

  resources :profiles, only: [ :show, :create, :update, :destroy ] do
    post :change_proportion, on: :member
    post :toggle_required, on: :member
  end

  resources :entities, only: [ :show, :create, :update, :destroy ] do
    post :change_parent, on: :member
    post :change_rec_count, on: :member
  end

  resources :attrs, only: [ :show, :create, :update, :destroy ] do
    post :toggle_transient, on: :member
    post :setup_profile, on: :member
  end

  resources :attr_vals, only: [ :create, :destroy ] do
    post :setup_conditions, on: :member
  end

  resources :conditions, only: [ :create, :destroy ]

end

app/models/condition.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

class Condition < ActiveRecord::Base
  belongs_to :attr_val
  belongs_to :attr

  JOIN_OR = 'or'
  JOIN_AND = 'and'

  OP_IS_NULL = 'isnull'
  OP_IS_NOT_NULL = 'notnull'
  OP_LESS_THAN = 'lt'
  OP_LESS_THAN_OR_EQUAL_TO = 'le'
  OP_EQUAL_TO = 'eq'
  OP_NOT_EQUAL_TO = 'ne'
  OP_GREATER_THAN_OR_EQUAL_TO = 'ge'
  OP_GREATER_THAN = 'gt'
  OP_EVENLY_DIVISIBLE_BY = 'ed'
  OP_NOT_EVENLY_DIVISIBLE_BY = 'nd'

  COMMON_OPS =      [ OP_IS_NULL, OP_IS_NOT_NULL, OP_EQUAL_TO, OP_NOT_EQUAL_TO ]
  COMPARABLE_OPS =  [ OP_LESS_THAN, OP_LESS_THAN_OR_EQUAL_TO, OP_GREATER_THAN_OR_EQUAL_TO, OP_GREATER_THAN ]
  NUMBER_ONLY_OPS = [ OP_EVENLY_DIVISIBLE_BY, OP_NOT_EVENLY_DIVISIBLE_BY ]

  DATA_TYPE_OPS = { Attr::TYPE_BOOLEAN =>         COMMON_OPS,
                    Attr::TYPE_INT =>             COMMON_OPS + COMPARABLE_OPS + NUMBER_ONLY_OPS,
                    Attr::TYPE_DECIMAL =>         COMMON_OPS + COMPARABLE_OPS + NUMBER_ONLY_OPS,
                    Attr::TYPE_DATE =>            COMMON_OPS + COMPARABLE_OPS,
                    Attr::TYPE_DATETIME =>        COMMON_OPS + COMPARABLE_OPS,
                    Attr::TYPE_ENUM =>            COMMON_OPS,
                    Attr::TYPE_STRING_TEMPLATE => []
  }

  before_validation :clear_nullop_value

  validate :validate_op
  validate :validate_value

  validates :join_using, inclusion: { in: [ JOIN_OR, JOIN_AND ] },
            allow_nil: true
  
  validate :ensure_no_cyclical_deps


  def to_s(options = {})
    arr = []
    arr << join_using unless join_using.blank? || options[:hide_join]

    if attr.entity == attr_val.attr.entity
      arr << attr.name

    else
      arr << "#{attr.entity.name}.#{attr.name}"
    end

    arr << op
    arr << value

    arr.join ' '
  end

  def matches(hsh)
    k = attr.entity == attr_val.attr.entity ?
        attr.name :
        "#{attr.entity.name}.#{attr.name}"

    if hsh.key? k
      v = hsh[k]

      if (op == OP_IS_NULL && v.nil?) || (op == OP_IS_NOT_NULL && ! v.nil?)
        match = true

      elsif (op == OP_IS_NULL && ! v.nil?) || (op == OP_IS_NOT_NULL && v.nil?)
        match = false

      else
        match = case attr.data_type
          when Attr::TYPE_BOOLEAN then  matches_boolean(v)
          when Attr::TYPE_INT then      matches_int(v)
          when Attr::TYPE_DECIMAL then  matches_decimal(v)
          when Attr::TYPE_DATE then     matches_date(v)
          when Attr::TYPE_DATETIME then matches_datetime(v)
          when Attr::TYPE_ENUM then     matches_enum(v)
          else raise "cannot evaluate #{k} - unhandled data type '#{attr.data_type}'"
        end
      end

      match

    else
      raise "cannot evaluate #{k} - value is missing"
    end
  end

  private

    def clear_nullop_value
      self.value = nil if op == OP_IS_NULL || op == OP_IS_NOT_NULL
    end

    def validate_op
      unless DATA_TYPE_OPS[attr.data_type].include?(op)
        errors.add(:op, "is invalid for data type '#{attr.data_type}'")
      end
    end

    def validate_value
      unless op == OP_IS_NULL || op == OP_IS_NOT_NULL
        begin
          case attr.data_type
            when Attr::TYPE_BOOLEAN then          raise unless value =~ Attr::REGEX_BOOLEAN
            when Attr::TYPE_INT then              Integer(value)
            when Attr::TYPE_DECIMAL then          Float(value)
            when Attr::TYPE_DATE then             Date.strptime(value, Attr::DATE_PATTERN)
            when Attr::TYPE_DATETIME then         Date.strptime(value, Attr::DATE_PATTERN)  # same as TYPE_DATE, for now
            when Attr::TYPE_ENUM then             raise unless value =~ Attr::REGEX_ENUM
            when Attr::TYPE_STRING_TEMPLATE then  raise unless value =~ Attr::REGEX_STR_TEMPLATE
            else                                  raise "unhandled data type '#{attr.data_type}'"
          end
        rescue
          errors.add(:value, 'is invalid')
        end
      end
    end

    def matches_boolean(v)
      b = case value
        when 'true' then  true
        when 'false' then false
        else              raise "invalid boolean value '#{value}'"
      end

      case op
        when OP_EQUAL_TO then     v == b
        when OP_NOT_EQUAL_TO then v != b
        else                      raise "unhandled boolean operation '#{op}'"
      end
    end

    def matches_int(v)
      i = value.to_i
      case op
        when OP_LESS_THAN then                v < i
        when OP_LESS_THAN_OR_EQUAL_TO then    v <= i
        when OP_EQUAL_TO then                 v == i
        when OP_NOT_EQUAL_TO then             v != i
        when OP_GREATER_THAN_OR_EQUAL_TO then v >= i
        when OP_GREATER_THAN then             v > i
        when OP_EVENLY_DIVISIBLE_BY then      v % i == 0
        when OP_NOT_EVENLY_DIVISIBLE_BY then  v % i != 0
        else                                  raise "unhandled int operation '#{op}'"
      end
    end

    def matches_decimal(v)
      f = value.to_f
      case op
        when OP_LESS_THAN then                v < f
        when OP_LESS_THAN_OR_EQUAL_TO then    v <= f
        when OP_EQUAL_TO then                 v == f
        when OP_NOT_EQUAL_TO then             v != f
        when OP_GREATER_THAN_OR_EQUAL_TO then v >= f
        when OP_GREATER_THAN then             v > f
        when OP_EVENLY_DIVISIBLE_BY then      (v % f).round(10) == 0
        when OP_NOT_EVENLY_DIVISIBLE_BY then  (v % f).round(10) != 0
        else                                  raise "unhandled decimal operation '#{op}'"
      end
    end

    def matches_date(v)
      d = Date.strptime(value, Attr::DATE_PATTERN)
      case op
        when OP_LESS_THAN then                v < d
        when OP_LESS_THAN_OR_EQUAL_TO then    v <= d
        when OP_EQUAL_TO then                 v == d
        when OP_NOT_EQUAL_TO then             v != d
        when OP_GREATER_THAN_OR_EQUAL_TO then v >= d
        when OP_GREATER_THAN then             v > d
        else                                  raise "unhandled date operation '#{op}'"
      end
    end

    def matches_datetime(v)
      d = Date.strptime(value, Attr::DATE_PATTERN)
      start_of_day = DateTime.new(d.year, d.month, d.day, 0, 0, 0)
      end_of_day = DateTime.new(d.year, d.month, d.day, 23, 59, 59)
      case op
        when OP_LESS_THAN then                v < start_of_day
        when OP_LESS_THAN_OR_EQUAL_TO then    v <= end_of_day
        when OP_EQUAL_TO then                 v >= start_of_day && v <= end_of_day
        when OP_NOT_EQUAL_TO then             v < start_of_day || v > end_of_day
        when OP_GREATER_THAN_OR_EQUAL_TO then v >= start_of_day
        when OP_GREATER_THAN then             v > end_of_day
        else                                  raise "unhandled datetime operation '#{op}'"
      end
    end

    def matches_enum(v)
      case op
        when OP_EQUAL_TO then     v == value
        when OP_NOT_EQUAL_TO then v != value
        else                      raise "unhandled enum operation '#{op}'"
      end
    end

    def ensure_no_cyclical_deps
      traverse_dependent_attrs(attr) do |a|
        if a == attr_val.attr
          errors.add(:attr, 'detected cyclical dependency')
          break
        end
      end
    end

    def traverse_dependent_attrs(attr, &block)
      raise 'block required' unless block_given?

      attr.attr_vals.each do |attr_val|
        attr_val.attr_dependencies.each do |a|
          block.yield(a)
          traverse_dependent_attrs a, &block
        end
      end
    end
end

app/controllers/conditions_controller.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

require 'logging'

class ConditionsController < ApplicationController
  include Logging

  before_action :authenticate_user!
  before_action :verify_owner!, only: :create
  before_action :set_condition, only: :destroy

  respond_to :html

  # def index
  #   @conditions = Condition.all
  #   respond_with(@conditions)
  # end

  # def show
  #   respond_with(@condition)
  # end

  # def new
  #   @condition = Condition.new
  #   respond_with(@condition)
  # end

  # def edit
  # end

  def create
    begin
      condition = Condition.create(condition_params)
      @error = condition.errors.values.join('; ') if condition.errors.any?

    rescue Exception => e
      @error = e.class.to_s
      log_error e
    end

    do_ajax_response condition_params[:attr_val_id]
  end

  # def update
  #   @condition.update(condition_params)
  #   respond_with(@condition)
  # end

  def destroy
    attr_val_id = @condition.attr_val_id
    @condition.destroy
    do_ajax_response attr_val_id
  end

  private
    def set_condition
      @condition = Condition.find(params[:id])
    end

    def do_ajax_response(attr_val_id)
      @attr_val = AttrVal.find(attr_val_id)
      respond_to do |format|
        format.js { render layout: false }
      end
    end

    def verify_owner!
      attr_val_id = condition_params[:attr_val_id]
      if attr_val_id
        attr_val = AttrVal.find(attr_val_id)
        unless attr_val && attr_val.attr.entity.data_set.user == current_user
          redirect_to root_url
        end

      else
        redirect_to root_url
      end
    end

    def condition_params
      params.require(:condition).permit(:attr_val_id, :attr_id, :negated, :op, :value, :join_using)
    end
end

app/helpers/conditions_helper.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

module ConditionsHelper
  def build_condition_attrs_list(attr_val)
    arr = []
    entity = attr_val.attr.entity
    while entity do
      entity.attrs.each do |attr|
        if is_usable_in_conditions?(attr) && attr != attr_val.attr
          key = entity == attr_val.attr.entity ? attr.name : "#{entity.name}.#{attr.name}"
          arr << [key, attr.id]
        end
      end
      entity = entity.parent
    end
    arr
  end

  def build_condition_join_list
    arr = []
    arr << [ 'and', Condition::JOIN_AND ]
    arr << [ 'or',  Condition::JOIN_OR ]
    arr
  end

  def build_condition_operators_list(data_type)
    arr = []

    if data_type == Attr::TYPE_INT || data_type == Attr::TYPE_DECIMAL || data_type == Attr::TYPE_DATE || data_type == Attr::TYPE_DATETIME
      arr << [ 'is less than',                Condition::OP_LESS_THAN ]
      arr << [ 'is less than or equal to',    Condition::OP_LESS_THAN_OR_EQUAL_TO ]
      arr << [ 'is equal to',                 Condition::OP_EQUAL_TO ]
      arr << [ 'is not equal to',             Condition::OP_NOT_EQUAL_TO ]
      arr << [ 'is greater than or equal to', Condition::OP_GREATER_THAN_OR_EQUAL_TO ]
      arr << [ 'is greater than',             Condition::OP_GREATER_THAN ]

      if data_type == Attr::TYPE_INT || data_type == Attr::TYPE_DECIMAL
        arr << [ 'is evenly divisible by',      Condition::OP_EVENLY_DIVISIBLE_BY ]
        arr << [ 'is not evenly divisible by',  Condition::OP_NOT_EVENLY_DIVISIBLE_BY ]
      end

    elsif data_type == Attr::TYPE_BOOLEAN || data_type == Attr::TYPE_ENUM
      arr << [ 'is',      Condition::OP_EQUAL_TO ]
      arr << [ 'is not',  Condition::OP_NOT_EQUAL_TO ]
    end

    arr << [ 'is null',     Condition::OP_IS_NULL ]
    arr << [ 'is not null', Condition::OP_IS_NOT_NULL ]

    arr
  end

  private
    def is_usable_in_conditions?(attr)
      attr.data_type != Attr::TYPE_STRING_TEMPLATE
    end
end

app/views/conditions/_attr_info.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- each_available_attribute_for(attr) do |a|
  %div{ data: { id: a.id, type: a.data_type } }
    .condition_val
      - if a.data_type == Attr::TYPE_ENUM
        = select_tag 'condition[value]', options_for_select(available_enum_values(a)), class: 'lit'
      - elsif a.data_type == Attr::TYPE_BOOLEAN
        = select_tag 'condition[value]', options_for_select(%w(true false)), class: 'lit'
      - else
        = text_field_tag 'condition[value]', '', class: 'lit'

app/views/conditions/_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- if attr_val.conditions.any? || (params[:controller] == 'attr_vals' && params[:action] == 'setup_conditions')
  %table.conditions
    - attr_val.conditions.each_with_index do |c, i|
      %tr
        %td.code= c.to_s(hide_join: i == 0)
        %td= link_to 'X', c, :method => :delete, :remote => true, :class => 'destroy', :data => { :confirm => 'Are you sure?' }

  = form_tag(conditions_path, remote: true, class: 'new_condition') do
    = hidden_field_tag 'condition[attr_val_id]', attr_val.id
    - if attr_val.conditions.any?
      = select_tag 'condition[join_using]', options_for_select(build_condition_join_list)
    = select_tag 'condition[attr_id]', options_for_select(build_condition_attrs_list(attr_val)), class: 'condition_attr'
    .condition_op
    .condition_val
    = submit_tag 'Save'
    %span.error

- else
  No conditions specified.
  = link_to 'Click here to add conditions.', setup_conditions_attr_val_path(attr_val.id), :method => :post, :remote => true

app/views/conditions/_op_templates.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- Attr.all_data_types.each do |data_type|
  %div{ data: { type: data_type } }
    = select_tag 'condition[op]', options_for_select(build_condition_operators_list(data_type))

app/views/conditions/create.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

var error = "<%= @error %>";
var container = $("#avc_form_<%= @attr_val.id %>");

if (error != '') {
    $(container).find('span.error').html(error);

} else {
    $(container).html("<%= j render(partial: 'conditions/form', locals: { attr_val: @attr_val }) %>");
    var form = $(container).children('form.new_condition').first();
    updateOpSelect(form);
    updateValueInput(form);
}

app/views/conditions/destroy.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

var container = $("#avc_form_<%= @attr_val.id %>");
$(container).html("<%= j render(partial: 'conditions/form', locals: { attr_val: @attr_val }) %>");

var form = $(container).children('form.new_condition').first();
updateOpSelect(form);
updateValueInput(form);