config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'data_sets#index', as: 'authenticated_root'
  end

  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :data_sets, only: [ :index, :show, :create, :update, :destroy ] do
    post :build, on: :member
    post :retrieve_build, on: :member
    get :build_status, on: :member
    post :cancel_build, on: :member
  end

  resources :profiles, only: [ :show, :create, :update, :destroy ] do
    post :change_proportion, on: :member
    post :toggle_required, on: :member
  end

  resources :entities, only: [ :show, :create, :update, :destroy ] do
    post :change_parent, on: :member
    post :change_rec_count, on: :member
  end

  resources :attrs, only: [ :show, :create, :update, :destroy ] do
    post :toggle_transient, on: :member
    post :setup_profile, on: :member
  end

  resources :attr_vals, only: [ :create, :destroy ] do
    post :setup_conditions, on: :member
  end

  resources :conditions, only: [ :create, :destroy ]

end

app/models/profile.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

class Profile < ActiveRecord::Base
  belongs_to :entity

  has_many :attr_vals, dependent: :delete_all

  validates :name, format: { with: /\A[a-zA-Z][a-zA-Z0-9 ]*\z/ }  # keep in sync with validateProfileName() in entities.js

  def to_s
    name
  end
end

app/controllers/profiles_controller.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

require 'logging'

class ProfilesController < ApplicationController
  include Logging

  before_action :authenticate_user!
  before_action :verify_owner!, only: :create
  before_action :set_profile, only: [:show, :update, :destroy, :change_proportion, :toggle_required]

  respond_to :html

  # def index
  #   @profiles = Profile.all
  #   respond_with(@profiles)
  # end

  def show
    respond_with(@profile)
  end

  # def new
  #   @profile = Profile.new
  #   respond_with(@profile)
  # end
  #
  # def edit
  # end

  def create
    begin
      profile = Profile.create(profile_params)
      @error = profile.errors.values.join('; ') if profile.errors.any?

    rescue Exception => e
      @error = e.class.to_s
      log_error e
    end

    do_ajax_response profile_params[:entity_id]
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    entity_id = @profile.entity_id
    @profile.destroy
    do_ajax_response entity_id
  end

  def change_proportion
    p = profile_params[:proportion].to_i
    if p >= 0 && p <= 100
      @profile.proportion = profile_params[:proportion]
      @profile.save
    end
    do_ajax_response @profile.entity_id
  end

  def toggle_required
    @profile.required = params[:required] == 'yes'
    @profile.save
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def do_ajax_response(entity_id)
      @profiles = Profile.where(entity_id: entity_id)
      respond_to do |format|
        format.js { render layout: false }
      end
    end

    def profile_params
      params.require(:profile).permit(:entity_id, :name, :desc, :proportion)
    end

  def verify_owner!
    entity_id = profile_params[:entity_id]
    if entity_id
      entity = Entity.find(entity_id)
      unless entity && entity.data_set.user == current_user
        redirect_to root_url
      end

    else
      redirect_to root_url
    end
  end
end

app/helpers/profiles_helper.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

module ProfilesHelper
  def build_proportions_list(profile)
    used_by_others = 0
    profile.entity.profiles.each do |p|
      used_by_others += p.proportion unless p == profile || p.proportion.blank?
    end

    max = 100 - used_by_others

    arr = []
    for i in 0 .. max do
      arr << [ "#{i}%", i ]
    end
    arr
  end

  def build_profile_attributes_list(profile)
    profile.entity.attrs.collect { |a| [a.name, a.id] }
  end
end

app/views/profiles/_change_proportion_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= form_tag(change_proportion_profile_path(profile), remote: true, class: 'auto_submit') do
  = select_tag 'profile[proportion]', options_for_select(build_proportions_list(profile), profile.proportion)

app/views/profiles/_list.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- if profiles.any?
  %table.index
    %tr
      %th Name
      %th Proportion
      %th Required?
      %th

    - profiles.each do |profile|
      %tr
        %td= link_to profile.name, profile
        %td= render partial: 'profiles/change_proportion_form', locals: { profile: profile }
        %td= render partial: 'profiles/toggle_required_form', locals: { profile: profile }
        %td= link_to 'Destroy', profile, :method => :delete, :remote => true, :data => { :confirm => 'Are you sure?' }

app/views/profiles/_toggle_required_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= form_tag(toggle_required_profile_path(profile), remote: true, class: 'auto_submit') do
  = check_box_tag 'required', 'yes', profile.required?

app/views/profiles/change_proportion.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#profiles').html("<%= j render(partial: 'list', locals: { profiles: @profiles }) %>");

app/views/profiles/create.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

var error = "<%= @error %>";
if (error != '') {
    $('#new_profile_form').find('span.error').html(error);

} else {
    $('#new_profile_form').find('span.error').html('');
    $('#profile_name').val('');
    $('#profiles').html("<%= j render(partial: 'list', locals: { profiles: @profiles }) %>");
}

app/views/profiles/destroy.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#profiles').html("<%= j render(partial: 'list', locals: { profiles: @profiles }) %>");

app/views/profiles/show.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

%h2 '#{@profile.name}' profile

- content_for :path do
  %ul
    %li= link_to @profile.entity.data_set.name, @profile.entity.data_set
    %li /
    %li= link_to @profile.entity.name, @profile.entity
    %li /
    %li= link_to @profile.name, @profile

= form_for @profile do |f|
  = f.label :name, 'Rename Profile to:'
  = f.text_field :name
  = f.submit 'Rename'

%br

= form_tag(setup_profile_attr_path, remote: true, id: 'attr_select_form', class: 'auto_submit') do
  .instructions Select an attribute from the list below for which to create a profile-specific value domain.
  = hidden_field_tag 'profile_id', @profile.id
  = select_tag 'attr_id', options_for_select(build_profile_attributes_list(@profile)), prompt: '--select attribute--'

#attr_form

#attr_vals= render partial: 'attr_vals/list', locals: { attr_vals: @profile.attr_vals }

- content_for :resources do
  #condition_op_templates= render partial: 'conditions/op_templates'
  #valid_domain_attr_info