config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'data_sets#index', as: 'authenticated_root'
  end

  root 'home#index'

  get 'home/index'

  devise_for :users

  resources :data_sets, only: [ :index, :show, :create, :update, :destroy ] do
    post :build, on: :member
    post :retrieve_build, on: :member
    get :build_status, on: :member
    post :cancel_build, on: :member
  end

  resources :profiles, only: [ :show, :create, :update, :destroy ] do
    post :change_proportion, on: :member
    post :toggle_required, on: :member
  end

  resources :entities, only: [ :show, :create, :update, :destroy ] do
    post :change_parent, on: :member
    post :change_rec_count, on: :member
  end

  resources :attrs, only: [ :show, :create, :update, :destroy ] do
    post :toggle_transient, on: :member
    post :setup_profile, on: :member
  end

  resources :attr_vals, only: [ :create, :destroy ] do
    post :setup_conditions, on: :member
  end

  resources :conditions, only: [ :create, :destroy ]

end

app/models/entity.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

require 'logging'

class Entity < ActiveRecord::Base
  include Logging

  belongs_to :data_set
  belongs_to :parent, foreign_key: 'parent_entity_id', class_name: 'Entity'

  has_many :children, foreign_key: 'parent_entity_id', class_name: 'Entity', dependent: :nullify
  has_many :attrs, dependent: :delete_all
  has_many :profiles, dependent: :delete_all

  after_update :adjust_domain_refs
  before_save :adjust_parent_entity_id

  validates :name, format: { with: /\A[a-z]\w*\z/ }  # keep in sync with validateEntityName() in data_sets.js
  validates :min_recs, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :max_recs, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  validate :validate_name
  validate :max_recs_gte_min_recs

  def to_s
    name
  end

  def fully_qualified_name
    "#{data_set.name}:#{name}"
  end

  def branch_along_which_exists(entity)
    while entity.parent
      if entity.parent == self
        return entity

      else
        entity = entity.parent
      end
    end

    nil
  end

  def has_descendant(entity)
    branch_along_which_exists(entity) != nil
  end

  def create_table_stmt(options = {})
    arr = [ 'id int not null primary key' ]

    arr << "#{parent.name}_id int not null" if parent

    attrs.each do |a|
      arr << "#{a.name} #{a.sql_data_type(options)}" unless a.transient?
    end

    if parent
      arr << "INDEX fk_index (#{parent.name}_id)"
      arr << "FOREIGN KEY (#{parent.name}_id) REFERENCES #{parent.name}(id) ON DELETE CASCADE"
    end

    "create table #{name} (#{arr.join(', ')});\n"
  end

  def csv_headers
    "#{ordered_attrs_for_export.join(',')}\n"
  end

  def ordered_attrs_for_export
    unless @export_attrs
      arr = [ 'id' ]

      arr << "#{parent.name}_id" if parent

      attrs.each do |a|
        arr << a.name unless a.transient?
      end

      @export_attrs = arr.collect{ |item| item.to_sym }
    end

    @export_attrs
  end

  def fabricate_record(profile_id, parent = nil, options = {})
    rec = {}
    rec["#{parent[:entity_key]}_id".to_sym] = parent[:rec][:id] if parent

    attrs_in_eval_order(profile_id).each do |attr|
      attr_vals_hsh = attr.attr_vals_by_condition_count(profile_id)

      if profile_id && attr_vals_hsh.empty?
        # profile exists and is active, but does not override this attribute.
        # use profile-less value domain, if any exist
        attr_vals_hsh = attr.attr_vals_by_condition_count
      end

      if attr_vals_hsh.any?
        hsh = format_attrs_for_evaluation(rec, parent)
        val = nil

        # process tiers of attr_vals, where each tier is identified by the number of conditions each attr_val
        # has.  highest tiers - those with the most conditions - are processed first.  as soon as one attr_val
        # matches, it *and all other matching attr_val items from the same tier* are collected.  later, if there
        # are multiple matching attr_val items, then one is picked at random.  this will ensure that if there
        # are multiple attr_vals with no conditions (which will always match), that any of them may be used.
        # without this, only the first matching attr_val would be used.

        matching_attr_vals = []
        attr_vals_hsh.keys.sort.reverse.each do |k|
          attr_vals_hsh[k].each do |attr_val|
            matching_attr_vals << attr_val if attr_val.matches_condition(hsh)
          end
          break if matching_attr_vals.any?
        end

        if matching_attr_vals.any?
          attr_val = matching_attr_vals[rand(matching_attr_vals.size)]
          val = attr_val.evaluate(hsh, options)
        end

        rec[attr.name.to_sym] = val

      else
        # no user-configured value domains exist.  use the default value domain
        rec[attr.name.to_sym] = attr.generate_default_value
      end
    end

    rec
  end

  def each_descendant_entity(entity = nil, &block)
    raise 'block required' unless block_given?

    entity = self if entity.nil?

    entity.children.each do |child|
      yield child
      each_descendant_entity(child, &block)
    end
  end

  private
    def adjust_domain_refs
      return if name == name_was

      attr_names = attrs.collect{ |a| a.name }.join('|')
      regex = /\b#{name_was}\.(#{attr_names})\b/
      str_template_regex = /(?<!\\)\{#{name_was}\.(#{attr_names})\}/

      # only descendant entities will have domain attribute references that include the entity name component
      each_descendant_entity do |entity|
        entity.attrs.each do |attr|
          next unless Attr::attr_ref_types.include?(attr.data_type)

          attr.attr_vals.each do |attr_val|
            if attr.data_type == Attr::TYPE_STRING_TEMPLATE && attr_val.domain =~ str_template_regex
              new_domain = attr_val.domain.gsub(str_template_regex, "{#{name}.\\1}")
              attr_val.update(domain: new_domain)

            elsif attr.data_type != Attr::TYPE_STRING_TEMPLATE && attr_val.domain =~ regex
              new_domain = attr_val.domain.gsub(regex, "#{name}.\\1")
              attr_val.update(domain: new_domain)
            end
          end
        end
      end
    end

    # generate a hash containing all generated attributes and values for this record
    # and its parent entities, structured in such a way that can be easily consumed by
    # the condition-matching logic
    def format_attrs_for_evaluation(rec, parent)
      hsh = {}

      rec.each_pair do |attr_name, attr_val|
        hsh[attr_name.to_s] = attr_val unless attr_name == :id
      end

      while parent
        parent[:rec].each_pair do |attr_name, attr_val|
          hsh["#{parent[:entity_key]}.#{attr_name}"] = attr_val unless attr_name == :id
        end
        parent = parent[:parent]
      end

      hsh
    end

    # sort attributes in the order in which they should be evaluated.  ensure that attributes that depend on others
    # are populated after their dependencies have been generated.
    # this information is cached to improve performance, and will remain as long as this instance of the entity is used
    def attrs_in_eval_order(profile_id)
      @attrs_in_eval_order = {} unless @attrs_in_eval_order

      unless @attrs_in_eval_order[profile_id]
        arr = []        # final list of attributes to send back
        dep_arr = []    # list of attributes with dependencies

        attrs.each do |attr|
          attr_vals = attr.attr_vals.where(profile_id: profile_id)
          attr_vals = attr.attr_vals if profile_id && attr_vals.empty?

          dependencies = []
          attr_vals.each do |attr_val|
            attr_val.attr_dependencies.each do |a|
              dependencies << a if a.entity == self
            end
          end
          dependencies.uniq!

          if dependencies.any?
            dep_arr << { attr: attr, dependencies: dependencies }

          else
            arr << attr     # no dependencies, so add to final list
          end
        end

        # process attributes with dependencies, adding them at the end ONLY if all dependencies exist in the list
        while dep_arr.any?
          dep_arr.each_index do |i|
            hsh = dep_arr[i]
            all_exist = true

            hsh[:dependencies].each do |attr|
              unless arr.include? attr
                all_exist = false
                break
              end
            end

            if all_exist
              arr << hsh[:attr]
              dep_arr.delete_at(i)
            end
          end
        end

        @attrs_in_eval_order[profile_id] = arr
      end

      @attrs_in_eval_order[profile_id]
    end

    def adjust_parent_entity_id
      self.parent_entity_id = nil if parent_entity_id.blank?
    end

    def validate_name
      if name.downcase == 'null'
        errors.add(:name, 'is reserved')
      end
    end

    def max_recs_gte_min_recs
      if min_recs > max_recs
        errors.add(:max_recs, 'must be greater than or equal to min_recs')
      end
    end
end

app/controllers/entities_controller.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.
require 'logging'

class EntitiesController < ApplicationController
  include Logging

  before_action :authenticate_user!
  before_action :verify_owner!, only: :create
  before_action :set_entity, only: [:show, :update, :destroy, :change_parent, :change_rec_count]

  respond_to :html

  # def index
  #   @entities = Entity.all
  #   respond_with(@entities)
  # end

  def show
    respond_with(@entity)
  end

  # def new
  #   @entity = Entity.new
  #   respond_with(@entity)
  # end
  #
  # def edit
  # end

  def create
    begin
      entity = Entity.create(entity_params)
      @error = entity.errors.values.join('; ') if entity.errors.any?

    rescue Exception => e
      @error = e.class.to_s
      log_error e
    end

    do_ajax_response entity_params[:data_set_id]
  end

  def update
    @entity.update(entity_params)
    respond_with(@entity)
  end

  def destroy
    data_set_id = @entity.data_set_id
    @entity.destroy
    do_ajax_response data_set_id
  end

  def change_parent
    parent_entity_id = entity_params[:parent_entity_id]
    do_save = parent_entity_id.blank?
    unless parent_entity_id.blank?
      do_save = Entity.find(parent_entity_id).data_set.user == current_user
    end

    if do_save
      unless parent_entity_id.blank?

        # the following prevents an impossible cyclical hierarchy, such that A -> B and B -> A

        new_parent = Entity.find(parent_entity_id)
        if is_descendant(@entity, new_parent)
          child = branch_along_which_exists(@entity, new_parent)
          child.parent_entity_id = @entity.parent_entity_id
          child.save
        end
      end

      @entity.parent_entity_id = parent_entity_id
      @entity.save
    end

    do_ajax_response @entity.data_set_id
  end

  def change_rec_count
    p = entity_params

    if p[:min_recs] && p[:max_recs]
      min = p[:min_recs].to_i
      max = p[:max_recs].to_i
      @entity.min_recs = min >= 1 ? min : 1
      @entity.max_recs = max >= min ? max : min
      @entity.save
    end

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    def branch_along_which_exists(entity, new_parent)
      entity.branch_along_which_exists new_parent
    end

    def is_descendant(entity, new_parent)
      entity.has_descendant new_parent
    end

    def set_entity
      @entity = Entity.find(params[:id])
    end

    def do_ajax_response(data_set_id)
      @entities = DataSet.find(data_set_id).entities_sorted_hierarchically
      respond_to do |format|
        format.js { render layout: false }
      end
    end

    def entity_params
      params.require(:entity).permit(:data_set_id, :parent_entity_id, :name, :desc, :min_recs, :max_recs)
    end

    def verify_owner!
      data_set_id = entity_params[:data_set_id]
      if data_set_id
        data_set = DataSet.find(data_set_id)
        unless data_set && data_set.user == current_user
          redirect_to root_url
        end

      else
        redirect_to root_url
      end
    end
end

app/helpers/entities_helper.rb
# Copyright 2015 The University of Vermont and State Agricultural
# College.  All rights reserved.
#
# Written by Matthew B. Storer <matthewbstorer@gmail.com>
#
# This file is part of Data Fabricator.
#
# Data Fabricator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Data Fabricator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

module EntitiesHelper
  def build_possible_parents_list(entity)
    arr = []
    arr << ['(none)', '']
    Entity.where(data_set_id: entity.data_set_id).each do |e|
      arr << [e.name, e.id] unless e.id == entity.id
    end
    arr
  end
end

app/views/entities/_change_parent_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= form_tag(change_parent_entity_path(entity), remote: true, class: 'auto_submit') do
  = select_tag 'entity[parent_entity_id]', options_for_select(build_possible_parents_list(entity), entity.parent_entity_id)

app/views/entities/_change_rec_counts_form.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

= form_tag(change_rec_count_entity_path(entity), remote: true, class: 'rec_count') do
  = label_tag 'entity[min_recs]', 'Min:'
  = text_field_tag 'entity[min_recs]', entity.min_recs, size: 4, id: nil, class: 'min_recs'
  = label_tag 'entity[max_recs]', 'Max:'
  = text_field_tag 'entity[max_recs]', entity.max_recs, size: 4, id: nil, class: 'max_recs'
  = submit_tag 'Save', disabled: true

app/views/entities/_list.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

- if entities.any?
  %table.index
    %tr
      %th Name
      %th Parent Entity
      %th Record Counts
      %th

    - entities.each do |entity|
      %tr
        %td= link_to entity.name, entity
        %td= render partial: 'entities/change_parent_form', locals: { entity: entity }
        %td{ id: "crc_form_#{entity.id}" }= render partial: 'entities/change_rec_counts_form', locals: { entity: entity }
        %td= link_to 'Destroy', entity, :method => :delete, :remote => true, :data => { :confirm => 'Are you sure?' }

app/views/entities/change_parent.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#entities').html("<%= j render(partial: 'list', locals: { entities: @entities }) %>");

app/views/entities/change_rec_count.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

var container = $("#crc_form_<%= @entity.id %>");
$(container).html("<%= j render partial: 'entities/change_rec_counts_form', locals: { entity: @entity } %>");

app/views/entities/create.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

var error = "<%= @error %>";
if (error != '') {
    $('#new_entity_form').find('span.error').html(error);

} else {
    $('#new_entity_form').find('span.error').html('');
    $('#entity_name').val('');
    $('#entities').html("<%= j render(partial: 'list', locals: { entities: @entities }) %>");
}

app/views/entities/destroy.js.erb
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

$('#entities').html("<%= j render(partial: 'list', locals: { entities: @entities }) %>");

app/views/entities/show.html.haml
// Copyright 2015 The University of Vermont and State Agricultural
// College.  All rights reserved.
//
// Written by Matthew B. Storer <matthewbstorer@gmail.com>
//
// This file is part of Data Fabricator.
//
// Data Fabricator is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Data Fabricator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Data Fabricator.  If not, see <http://www.gnu.org/licenses/>.

%h2 '#{@entity.fully_qualified_name}' entity

- content_for :path do
  %ul
    %li= link_to @entity.data_set.name, @entity.data_set
    %li /
    %li= link_to @entity.name, @entity

= form_for @entity do |f|
  = f.label :name, 'Rename Entity to:'
  = f.text_field :name
  = f.submit 'Rename'

%br

#new_attr_form
  = form_tag(attrs_path, remote: true) do
    = hidden_field_tag 'attr[entity_id]', @entity.id
    = label_tag 'attr[name]', 'New attribute:'
    = text_field_tag 'attr[name]'
    = label_tag 'attr[data_type]', 'Data type:'
    = select_tag 'attr[data_type]', options_for_select(Attr.all_data_types)
    = submit_tag 'Save'
    %span.error

#attrs= render partial: 'attrs/list', locals: { attrs: @entity.attrs }

%br

= form_tag(profiles_path, remote: true, id: 'new_profile_form') do
  = hidden_field_tag 'profile[entity_id]', @entity.id
  = label_tag 'profile[name]', 'New profile:'
  = text_field_tag 'profile[name]'
  = submit_tag 'Save'
  %span.error

#profiles= render partial: 'profiles/list', locals: { profiles: @entity.profiles }